#ifndef ADAPTER_CONFIG_H
#define ADAPTER_CONFIG_H

//#define ADAPTER_MCU_TYPE 2

#define ADAPTER_BUTTON_1  GPIO_NUM_0 // Use BOOT signal by default
#define ADAPTER_BUTTON_2  GPIO_NUM_4
#define ADAPTER_RGB_COUNT 4
#define ADAPTER_PORT_COUNT 1

#define ADAPTER_MANUFACTURER "HHL"
#define ADAPTER_PRODUCT "GC Pocket"
#define ADAPTER_STRING "GCP"

#define ADAPTER_FIRMWARE_VERSION 0x0004
#define ADAPTER_SETTINGS_VERSION 0x0003
#define ADAPTER_WEBUSB_URL "handheldlegend.github.io/gcp"

#endif